version: '3.9'
services:
  db:
    image: mysql:8.3.0
    command: mysqld --default_authentication_plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: docker
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: ${DB_PORT}
    ports:
      - ${DB_PORT}:${DB_PORT}

    expose:
      - ${DB_PORT}

    networks:
      - ecommerce-network

  ecommerce:
    image: guilhermebauer/ecommerce_app
    container_name: ecommerce_app
    build: .
    restart: always
    environment:
      TZ: America/Sao_Paulo
      SPRING_DATASOURCE_URL: jdbc:mysql://db:${DB_PORT}/${DB_NAME}?useSSL=false&useTimezone=true&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

    command: mvn spring-boot:run

    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge
